set(ZLIB_ROOT ${CMAKE_BINARY_DIR}/zlib/Linux/armhf)
set(ZLIB_TARGET_NAME ZLIB_PYRA)
set(ZLIB_BINARY_DIR ${ZLIB_ROOT})
set(ZLIB_INSTALL_DIR ${ZLIB_ROOT})
set(ZLIB_USE_STATIC_LIBS TRUE)
set(ZLIB_FOUND TRUE)
set(ZLIB_INCLUDE_DIRS ${ZLIB_ROOT}/include)
set(ZLIB_LIBRARIES z)
set(ZLIB_STATIC_LIBRARY_PATH ${ZLIB_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}z${CMAKE_STATIC_LIBRARY_SUFFIX})
set(ZLIB_SHARED_LIBRARY_PATH ${ZLIB_ROOT}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}z${CMAKE_SHARED_LIBRARY_SUFFIX})
set(ZLIB_SHARED_LIBRARY_DIR ${ZLIB_ROOT}/lib)
ExternalProject_Add(${ZLIB_TARGET_NAME}
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/lib/zlib
    BINARY_DIR ${ZLIB_BINARY_DIR}
    INSTALL_DIR ${ZLIB_INSTALL_DIR}
    UPDATE_DISCONNECTED TRUE
    CMAKE_ARGS --install-prefix ${ZLIB_INSTALL_DIR}
               -DCMAKE_INSTALL_LIBDIR=lib
               --toolchain ${CMAKE_TOOLCHAIN_FILE}
               -DCMAKE_BUILD_TYPE:STRING=Release
               -DCMAKE_POLICY_VERSION_MINIMUM=3.5
               -DZLIB_BUILD_TESTING=OFF
    BUILD_BYPRODUCTS ${ZLIB_STATIC_LIBRARY_PATH} ${ZLIB_SHARED_LIBRARY_PATH})
add_library(ZLIB::ZLIB STATIC IMPORTED)
file(MAKE_DIRECTORY ${ZLIB_INCLUDE_DIRS})
set_property(TARGET ZLIB::ZLIB PROPERTY IMPORTED_LOCATION ${ZLIB_STATIC_LIBRARY_PATH})
target_include_directories(ZLIB::ZLIB INTERFACE ${ZLIB_INCLUDE_DIRS})
add_dependencies(ZLIB::ZLIB ${ZLIB_TARGET_NAME})
