set(OPENAL_ROOT ${CMAKE_BINARY_DIR}/openal)
set(OPENAL_FOUND TRUE)
set(OPENAL_COMPILING_FROM_SRC TRUE)
set(OPENAL_INCLUDE_DIR ${OPENAL_ROOT}/include/AL)
set(OPENAL_LIBRARY ${OPENAL_ROOT}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}openal${CMAKE_SHARED_LIBRARY_SUFFIX})
set(OPENAL_VERSION_STRING 1.23.1)
ExternalProject_Add(OPENAL
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/lib/openal
    BINARY_DIR ${OPENAL_ROOT}
    INSTALL_DIR ${OPENAL_ROOT}
    UPDATE_DISCONNECTED TRUE
    CMAKE_ARGS --toolchain ${CMAKE_TOOLCHAIN_FILE}
               --install-prefix ${OPENAL_ROOT}
               -DCMAKE_INSTALL_LIBDIR=lib
               -DCMAKE_BUILD_TYPE:STRING=Release
               -DALSOFT_UTILS:BOOL=FALSE
               -DALSOFT_NO_CONFIG_UTIL:BOOL=TRUE
               -DALSOFT_EXAMPLES:BOOL=FALSE
               -DALSOFT_INSTALL_CONFIG:BOOL=FALSE
               -DALSOFT_INSTALL_HRTF_DATA:BOOL=FALSE
               -DALSOFT_INSTALL_AMBDEC_PRESETS:BOOL=FALSE
               -DALSOFT_INSTALL_EXAMPLES:BOOL=FALSE
               -DALSOFT_INSTALL_UTILS:BOOL=FALSE
               -DALSOFT_UPDATE_BUILD_VERSION:BOOL=TRUE
               -DALSOFT_CPUEXT_SSE:BOOL=FALSE
               -DALSOFT_CPUEXT_SSE2:BOOL=FALSE
               -DALSOFT_CPUEXT_SSE3:BOOL=FALSE
               -DALSOFT_CPUEXT_SSE4_1:BOOL=FALSE
               -DALSOFT_STATIC_LIBGCC:BOOL=FALSE
               -DALSOFT_STATIC_STDCXX:BOOL=FALSE
               -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    BUILD_BYPRODUCTS ${OPENAL_LIBRARY})
add_library(OpenAL::OpenAL SHARED IMPORTED)
add_dependencies(OpenAL::OpenAL OPENAL)
file(MAKE_DIRECTORY ${OPENAL_INCLUDE_DIR})
set_target_properties(OpenAL::OpenAL PROPERTIES IMPORTED_LOCATION ${OPENAL_LIBRARY})
target_include_directories(OpenAL::OpenAL INTERFACE ${OPENAL_INCLUDE_DIR})
target_link_directories(OpenAL::OpenAL INTERFACE ${OPENAL_ROOT}/lib)
